- hosts: localhost
  gather_facts: no
  tasks:
        - name: Add user
          user:
               name: johnd
               comment: John Doe
               uid: 1040
               group: wheel
